version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: scripts/install_nginx.sh
      timeout: 15
      runas: root
  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 1
      runas: root
