version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mkdir -p output
      - cp index.html output/

  post_build:
    commands:
      - echo "Build completed. Contents of output directory:"
      - ls -l output/

artifacts:
  files:
    - output/index.html
